services:
  frontend:
    container_name: frontend
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_PROXY_TARGET: http://backend:8080

  postgres:
    image: postgres:alpine3.22
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: "no"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      BROKER_URL: amqp://${RABBITMQ_DEFAULT_USER:-task_tracker}:${RABBITMQ_DEFAULT_PASS:-task_tracker}@broker:5672/
      BROKER_EXCHANGE: task_events
    depends_on:
      - postgres
      - broker
    ports:
      - "8081:8080"
    expose:
      - "8080"
    restart: unless-stopped

  broker:
    image: rabbitmq:3-management-alpine
    container_name: broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-task_tracker}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-task_tracker}
    volumes:
      - ./broker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - broker_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  frontend_node_modules:
  postgres_data:
  broker_data:
